name: Track Lead Time

on:
  pull_request:
    types: [closed]

jobs:
  track-lead-time:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Calculate Lead Time
        env:
          FIRST_COMMIT_TIME: ${{ github.event.pull_request.created_at }}
          MERGE_TIME: ${{ github.event.pull_request.merged_at }}
        run: |
          lead_time=$(( $(date -d "$MERGE_TIME" +%s) - $(date -d "$FIRST_COMMIT_TIME" +%s) ))
          echo "Lead Time: $lead_time seconds"
          echo "lead_time_seconds=$lead_time" >> "$GITHUB_STEP_SUMMARY"